import { newSession } from './bot.mjs';
const { page, logs, close } = await newSession();
const out = await page.evaluate(() => {
  const g = window.__wk; g.debugGoto(1); g.debugStep(90);
  const res = {};
  g.player.invuln = 0;
  g.spawnEnemy('mite', g.player.x + 3, g.player.z, false);
  g.debugStep(120);
  res.afterMite = { hp: g.player.hp, dmg: g.stats.damageTaken, mode: g.mode, invuln: g.player.invuln, enemies: g.enemies.map(e => [e.kind, +e.x.toFixed(1), +e.z.toFixed(1), e.hp]) };
  g.spawnEnemy('spitter', g.player.x + 10, g.player.z, false);
  g.debugStep(240);
  res.afterSpitter = { hp: g.player.hp, dmg: g.stats.damageTaken, bolts: g.projectiles.count };
  g.spawnEnemy('brute', g.player.x + 10, g.player.z + 3, false);
  g.debugStep(300);
  res.afterBrute = { hp: g.player.hp, dmg: g.stats.damageTaken, bolts: g.projectiles.count, states: g.enemies.map(e => [e.kind, e.state]) };
  return res;
});
console.log(JSON.stringify(out, null, 1));
console.log(logs.join('\n') || 'no console errors');
await close();
