import { serve, launch } from './harness.mjs';
import path from 'node:path';
const server = await serve(path.resolve('dist'));
const { browser, page, logs } = await launch({ width: 960, height: 540 });
await page.goto('http://127.0.0.1:4173/?debug');
await page.waitForTimeout(1200);
await page.evaluate(() => { const g = window.__wk; g.debugGoto(0); });
await page.waitForTimeout(3500);
const shot = (n) => page.screenshot({ path: `shots/diag-${n}.png` });
await page.evaluate(() => { window.__wk.ui.hide('banner'); document.getElementById('hud').style.display='none'; document.getElementById('banner').style.display='none'; });
await shot('a-all');
await page.evaluate(() => { window.__wk.gfx.bloom.enabled = false; });
await shot('b-nobloom');
await page.evaluate(() => { window.__wk.world.mycelium.lines.visible = false; });
await shot('c-nomyc');
await page.evaluate(() => { window.__wk.world.flora.group.visible = false; });
await shot('d-noflora');
console.log(logs.join('\n') || 'ok');
await browser.close(); server.close();
