import { serve, launch } from './harness.mjs';
import path from 'node:path';
const server = await serve(path.resolve('dist'));
const { browser, page, logs } = await launch({ width: 1280, height: 720 });
const wait = (ms) => page.waitForTimeout(ms);
const idx = Number(process.argv[2] ?? 0);
await page.goto('http://127.0.0.1:4173/?debug&nolock&scale=1&noadapt');
await wait(1500);
await page.screenshot({ path: 'shots/p-title.png' });
await page.evaluate((i) => { const g = window.__wk; g.debugGoto(i); g.god = true; }, idx);
await wait(5000);
await page.screenshot({ path: `shots/p-s${idx}-a.png` });
console.log(JSON.stringify(await page.evaluate(() => window.__wk.debugState())));
console.log(logs.join('\n') || 'no console errors');
await browser.close(); server.close();
