import { serve, launch } from './harness.mjs';
import path from 'node:path';
const server = await serve(path.resolve('dist'));
const { browser, page, logs } = await launch({ width: 1280, height: 720 });
const wait = (ms) => page.waitForTimeout(ms);
await page.goto('http://127.0.0.1:4173/?debug&scale=1&noadapt');
await wait(1000);
await page.evaluate(() => { const g = window.__wk; g.debugGoto(0); g.god = true; });
await wait(2000);
await page.evaluate(() => { for (const id of ['banner']) document.getElementById(id).style.display = 'none'; window.__wk.ui.clearSay(); });
await page.evaluate(() => { const g = window.__wk; g.debugCompleteNodes(); g.debugAt(0, 0); g.debugStep(120); g.player.res = 100; g.input.press('Space'); });
await wait(3500);
await page.screenshot({ path: 'shots/qa-s0-done.png' });
console.log(logs.join('\n') || 'no console errors');
await browser.close(); server.close();
