import { serve, launch } from './harness.mjs';
import path from 'node:path';
const server = await serve(path.resolve('dist'));
const { browser, page, logs } = await launch({ width: 1280, height: 720 });
const wait = (ms) => page.waitForTimeout(ms);
await page.goto('http://127.0.0.1:4173/?scale=0.8&noadapt');
await wait(2500);
await page.click('#btn-begin');
await wait(2500);
await page.screenshot({ path: 'shots/fm-prologue1.png' });
await page.keyboard.press('Enter'); await wait(3000);
await page.screenshot({ path: 'shots/fm-prologue2.png' });
await page.keyboard.press('Enter'); await wait(3500);
await page.keyboard.press('Enter'); await wait(4500);
await page.screenshot({ path: 'shots/fm-banner.png' });
await wait(6000);
await page.screenshot({ path: 'shots/fm-intro.png' });
console.log(logs.join('\n') || 'no console errors');
await browser.close(); server.close();
